sudo: required
language: generic 
services:
 - docker

before_install:
 - docker build -t reggieh08/react-test -f./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true reggieh08/react-test npm test

after_success:
 - docker build -t reggieh08/multi-client ./client
 - docker build -t reggieh08/multi-nginx ./nginx
 - docker build -t reggieh08/multi-server ./server
 - docker build -t reggieh08/multi-worker ./worker
 # log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin

 # Take those images and push them to docker hub
 - docker push reggieh08/multi-client
 - docker push reggieh08/multi-nginx
 - docker push reggieh08/multi-server
 - docker push reggieh08/multi-worker


  